FROM node:12 as builder

WORKDIR /frontend

COPY package.json ./package.json
RUN npm install
COPY . .

RUN npm run build

FROM nginx:latest
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /frontend/build /usr/share/nginx/html
COPY --from=builder /frontend/build /frontend/build

EXPOSE 80
CMD ["nginx","-g","daemon off;"]