version: "3.5"
services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./
    volumes:
      - /frontend/node_modules
      - ./:/frontend
    ports:
      - "80:80"
        #    stdin_open: true
